[package]
name = "clipboard-sync"
version = "0.1.0"
edition = "2021"
description = "Low-latency bidirectional clipboard synchronization between X11 and Wayland"
license = "MIT"
repository = "https://github.com/LengineerC/clipboard-sync"
readme = "README.md"

[dependencies]
xxhash-rust = { version = "0.8.10", features = ["xxh3"] }
chrono = "0.4.35"
memfd = "0.6.3"
libc = "0.2"
